controller_joint_names: ['', 'hip_fe_left_side_bl_biped_joint', 'upper_leg_left_joint', 'lower_leg_left_joint', 'hip_fe_right_side_bl_biped_joint', 'upper_leg_right_joint', 'lower_leg_right_joint', ]
